apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    {{- include "vcluster-istio.labels" . | nindent 4 }}
    istio-injection: {{ if .Values.mesh.enabled }}enabled{{ else }}disabled{{ end }}
