{{- if .Values.metricsDb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vcop.fullname" . }}-metrics-db-secret
  labels:
    {{- include "vcop.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics-db
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.metricsDb.credentials.dbName | quote }}
  POSTGRES_USER: {{ .Values.metricsDb.credentials.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.metricsDb.credentials.password | quote }}
{{- end }}
