apiVersion: v2
name: vcluster-istio
description: Opinionated Istio Ingress Gateway & Service Mesh entrypoint stack for vCluster
type: application
version: 1.2.0
appVersion: "1.24.2"
annotations:
  artifacthub.io/license: Apache-2.0
icon: https://raw.githubusercontent.com/istio/istio/master/logo/istio-bluenavy.svg
keywords:
  - istio
  - ingress
  - gateway
  - vcluster
  - service-mesh
  - cert-manager
home: https://github.com/jfelixfalcon/vcop
sources:
  - https://github.com/jfelixfalcon/vcop
maintainers:
  - name: Juan Felix-Falcon
    email: jfelixfalcon@gmail.com
