apiVersion: v2
name: vcop
description: Cloud-Native Virtual Cluster Operator & Operations Center (vCluster OSS v0.36)
type: application
version: 1.2.0
appVersion: "v1.2.0"
icon: https://raw.githubusercontent.com/loft-sh/vcluster/main/docs/static/media/vcluster-logo.svg
keywords:
  - vcluster
  - operator
  - kubernetes
  - multi-tenancy
  - devops
  - observability
home: https://github.com/jfelixfalcon/vcop
sources:
  - https://github.com/jfelixfalcon/vcop
maintainers:
  - name: Juan Felix-Falcon
    email: jfelixfalcon@gmail.com
