apiVersion: v1
kind: Namespace
metadata:
  name: vcop-system
  labels:
    app.kubernetes.io/name: vcop
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vc-operator-controller-manager
  namespace: vcop-system
  labels:
    app.kubernetes.io/name: vc-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vcop-operator
  namespace: vcop-system
  labels:
    app.kubernetes.io/name: vcop-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vcop-ui
  namespace: vcop-system
  labels:
    app.kubernetes.io/name: vcop-ui
