import type { PresetDetails } from './types';

export const DEFAULT_SIZING_TIERS: PresetDetails[] = [
  {
    id: 'normal',
    name: 'Normal Tier',
    cpu: '2 vCPU',
    memory: '4 GB RAM',
    storage: '10 GB NVMe',
    ha: false,
    badge: 'Standard',
    description: '1x etcd, 1x vCluster control plane, 1x CoreDNS. Efficient resource footprint for development and standard workloads.',
    isDefault: true,
    requestsCPU: '1',
    limitsCPU: '2',
    requestsMemory: '2Gi',
    limitsMemory: '4Gi',
    requestsStorage: '10Gi',
    pods: '15',
    services: '10',
    persistentVolumeClaims: '5',
    createdAt: '2026-09-08T12:00:00.000Z',
    updatedAt: '2026-09-08T12:00:00.000Z',
    updatedBy: 'System Default',
  },
  {
    id: 'ha',
    name: 'High Availability Tier',
    cpu: '6 vCPU',
    memory: '12 GB RAM',
    storage: '25 GB NVMe',
    ha: true,
    badge: 'Production HA',
    description: '3x etcd quorum, 3x vCluster control plane, 3x CoreDNS. Full redundancy and zero single points of failure.',
    isDefault: false,
    requestsCPU: '4',
    limitsCPU: '8',
    requestsMemory: '8Gi',
    limitsMemory: '16Gi',
    requestsStorage: '25Gi',
    pods: '35',
    services: '25',
    persistentVolumeClaims: '15',
    createdAt: '2026-09-08T12:00:00.000Z',
    updatedAt: '2026-09-08T12:00:00.000Z',
    updatedBy: 'System Default',
  },
  {
    id: 'small',
    name: 'Small Sandbox',
    cpu: '1 vCPU',
    memory: '2 GB RAM',
    storage: '5 GB NVMe',
    ha: false,
    badge: 'Lightweight',
    description: 'Minimal single-node footprint for quick tests, lightweight microservices, and student sandboxes.',
    isDefault: false,
    requestsCPU: '500m',
    limitsCPU: '1',
    requestsMemory: '1Gi',
    limitsMemory: '2Gi',
    requestsStorage: '5Gi',
    pods: '10',
    services: '5',
    persistentVolumeClaims: '3',
    createdAt: '2026-09-08T12:00:00.000Z',
    updatedAt: '2026-09-08T12:00:00.000Z',
    updatedBy: 'System Default',
  },
  {
    id: 'medium',
    name: 'Medium Performance',
    cpu: '4 vCPU',
    memory: '8 GB RAM',
    storage: '20 GB NVMe',
    ha: false,
    badge: 'Balanced',
    description: 'Balanced CPU and memory allocation for team staging environments and active development.',
    isDefault: false,
    requestsCPU: '2',
    limitsCPU: '4',
    requestsMemory: '4Gi',
    limitsMemory: '8Gi',
    requestsStorage: '20Gi',
    pods: '25',
    services: '15',
    persistentVolumeClaims: '10',
    createdAt: '2026-09-08T12:00:00.000Z',
    updatedAt: '2026-09-08T12:00:00.000Z',
    updatedBy: 'System Default',
  },
  {
    id: 'large',
    name: 'Large Enterprise',
    cpu: '8 vCPU',
    memory: '16 GB RAM',
    storage: '50 GB NVMe',
    ha: true,
    badge: 'High Compute',
    description: 'Heavy multi-tenant compute, large databases, and intensive CI/CD integration pipelines.',
    isDefault: false,
    requestsCPU: '8',
    limitsCPU: '16',
    requestsMemory: '16Gi',
    limitsMemory: '32Gi',
    requestsStorage: '50Gi',
    pods: '50',
    services: '30',
    persistentVolumeClaims: '20',
    createdAt: '2026-09-08T12:00:00.000Z',
    updatedAt: '2026-09-08T12:00:00.000Z',
    updatedBy: 'System Default',
  },
];

export const PRESETS: PresetDetails[] = DEFAULT_SIZING_TIERS;
